name: server_driven_ui_challenge
description: test for snapfi company

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sdui: ^0.1.198
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/poppins-ExtraBold.ttf
          weight: 800

